const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{karistiriciacik: 0},
	{paremetre: 0},
	{Ekzotermik: 0},
	{Endotermikbt: 0},
	{Çevrebt: 0},
	{Evrenbt: 0},
	{sistembt: 0},
	{OFFbt: 0},
	{gösterge: 0},
	{NH4Cl: 0},
	{CH3COONa: 0},
	{NH4Clspatul: 0},
	{CH3COONaspatul: 0},
	{arkabeher: 0},
	{önbeherdikkat: 0},
	{img: 0},
	{img2: 0},
	{img3: 0},
	{MasaKontur: 0},
	{Sicaklik: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	karistiriciacik: class extends self.ISpriteInstance {},
	paremetre: class extends self.ISpriteInstance {},
	Ekzotermik: class extends self.ISpriteInstance {},
	Endotermikbt: class extends self.ISpriteInstance {},
	Çevrebt: class extends self.ISpriteInstance {},
	Evrenbt: class extends self.ISpriteInstance {},
	sistembt: class extends self.ISpriteInstance {},
	OFFbt: class extends self.ISpriteInstance {},
	gösterge: class extends self.ISpriteInstance {},
	NH4Cl: class extends self.ISpriteInstance {},
	CH3COONa: class extends self.ISpriteInstance {},
	NH4Clspatul: class extends self.ISpriteInstance {},
	CH3COONaspatul: class extends self.ISpriteInstance {},
	arkabeher: class extends self.ISpriteInstance {},
	önbeherdikkat: class extends self.ISpriteInstance {},
	img: class extends self.ISpriteInstance {},
	img2: class extends self.ISpriteInstance {},
	img3: class extends self.ISpriteInstance {},
	MasaKontur: class extends self.ISpriteInstance {},
	Sicaklik: class extends self.ITextInstance {}
}